services:
  dicj-horaires:
    image: dicj-horaires:latest
    container_name: dicj-horaires
    environment:
      - ACCESS_TOKEN=allo
    # Put a .env file in the root directory with the ACCESS_TOKEN
    ports:
      - "4000:4000"
    volumes:
      - ./teachers:/app/teachers
    restart: unless-stopped
